Update Installation

diff --git a/uninstall/uninstall b/uninstall/uninstall
--- a/uninstall/uninstall
+++ b/uninstall/uninstall
@@ -1,67 +1,66 @@
 #!/bin/bash
-
-# Bashscript which is executed by bash when uninstalling the plugin
-# Use with caution and remember, that all systems may be different!
 #
-# Exit code must be 0 if executed successfull. 
-# Exit code 1 gives a warning but continues deinstallation.
+# Wird als User "root" ausgefuehrt, wenn das Plugin deinstalliert wird.
+# Entfernt den Homebridge-systemd-Dienst (mit dem isolierten hb-service),
+# raeumt Reste auf und loescht die Config-Backups.
 #
-# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-# Will be executed as user "root".
-# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+# Das isolierte Node.js + Homebridge liegen unter der persistenten Runtime
+# ($LBHOMEDIR/data/system/homebridge_runtime) - ausserhalb der Plugin-Ordner,
+# daher loescht der LoxBerry-Installer sie NICHT. Dieses Skript raeumt sie
+# deshalb selbst weg (kein npm noetig, einfach das Verzeichnis entfernen).
+# Das System-Node (apt, /usr/bin/node) bleibt bewusst stehen, da es von
+# anderen Komponenten genutzt werden koennte.
 #
-# You can use all vars from /etc/environment in this script.
+# Exit code 0 = ok, 1 = Warnung (Deinstallation laeuft weiter).
 #
-# We add 5 additional arguments when executing this script:
-# command <TEMPFOLDER> <NAME> <FOLDER> <VERSION> <BASEFOLDER>
-#
-# For logging, print to STDOUT. You can use the following tags for showing
-# different colorized information during plugin installation:
-#
-# <OK> This was ok!"
-# <INFO> This is just for your information."
-# <WARNING> This is a warning!"
-# <ERROR> This is an error!"
-# <FAIL> This is a fail!"
+# Argumente: command <TEMPFOLDER> <NAME> <FOLDER> <VERSION> <BASEFOLDER>
 
-# To use important variables from command line use the following code:
-COMMAND=$0    # Zero argument is shell command
-PTEMPDIR=$1   # First argument is temp folder during install
-PSHNAME=$2    # Second argument is Plugin-Name for scipts etc.
-PDIR=$3       # Third argument is Plugin installation folder
-PVERSION=$4   # Forth argument is Plugin version
-LBHOMEDIR=$5 # Comes from /etc/environment now. Fifth argument is
-              # Base folder of LoxBerry
+COMMAND=$0
+PTEMPDIR=$1
+PSHNAME=$2
+PDIR=$3
+PVERSION=$4
+LBHOMEDIR=$5
 
-# Combine them with /etc/environment
-PCGI=$LBPCGI/$PDIR
-PHTML=$LBPHTML/$PDIR
-PTEMPL=$LBPTEMPL/$PDIR
-PDATA=$LBPDATA/$PDIR
-PLOG=$LBPLOG/$PDIR # Note! This is stored on a Ramdisk now!
-PCONFIG=$LBPCONFIG/$PDIR
-PSBIN=$LBPSBIN/$PDIR
-PBIN=$LBPBIN/$PDIR
+HB_RUNTIME_DIR="$LBHOMEDIR/data/system/homebridge_runtime"
+HB_NODE_DIR="$HB_RUNTIME_DIR/nodejs"
+HB_NPM_GLOBAL="$HB_RUNTIME_DIR/npm-global"
+HB_SERVICE="$HB_NPM_GLOBAL/bin/hb-service"
+SERVICE_UNIT="/etc/systemd/system/homebridge.service"
 
-echo "<INFO> Command is: $COMMAND"
-echo "<INFO> Temporary folder is: $TEMPDIR"
-echo "<INFO> (Short) Name is: $PSHNAME"
-echo "<INFO> Installation folder is: $ARGV3"
-echo "<INFO> Plugin version is: $ARGV4"
-echo "<INFO> Plugin CGI folder is: $PCGI"
-echo "<INFO> Plugin HTML folder is: $PHTML"
-echo "<INFO> Plugin Template folder is: $PTEMPL"
-echo "<INFO> Plugin Data folder is: $PDATA"
-echo "<INFO> Plugin Log folder (on RAMDISK!) is: $PLOG"
-echo "<INFO> Plugin CONFIG folder is: $PCONFIG"
-echo "<INFO> Plugin SBIN folder is: $PSBIN"
-echo "<INFO> Plugin BIN folder is: $PBIN"
+echo "<INFO> Deinstalliere Homebridge-Dienst."
 
-echo "<INFO> Deinstallieren der Homebridge"
-echo "******************************************************TEST***********************************************" > /tmp/uninstall.test
-hb-service uninstall
+# Dienst stoppen (egal ob Unit-ExecStart noch gueltig ist).
+systemctl stop homebridge.service 2>/dev/null || true
 
-# Homebridge Plugins deinstallieren
-npm uninstall -g --unsafe-perm homebridge-config-ui-x
-npm uninstall -g --unsafe-perm homebridge
+# Bevorzugt sauber ueber das isolierte hb-service deinstallieren.
+export PATH="$HB_NODE_DIR/bin:$HB_NPM_GLOBAL/bin:$PATH"
+if [ -x "$HB_SERVICE" ]; then
+    "$HB_SERVICE" uninstall || true
+fi
+
+# Hart nachraeumen, falls das systemd-Unit noch existiert.
+if [ -f "$SERVICE_UNIT" ]; then
+    echo "<INFO> Entferne verbliebenes systemd-Unit."
+    systemctl disable --now homebridge.service 2>/dev/null || true
+    rm -f "$SERVICE_UNIT"
+    systemctl daemon-reload 2>/dev/null || true
+fi
+
+# Cleanup-Marker der Fremd-Node-Bereinigung entfernen, damit eine spaetere
+# Neuinstallation die Pruefung wieder von vorne durchfuehrt.
+rm -f "$LBHOMEDIR/data/system/homebridge_node_cleanup_done"
+
+# Config-Backups entfernen - sonst wuerde eine spaetere Neuinstallation ueber
+# postroot.sh eine alte Konfiguration wiederherstellen.
+rm -rf "$LBHOMEDIR/data/system/tmp/homebridge_config_backup"
+
+# Persistente Runtime (isoliertes Node.js + Homebridge) entfernen. Sie liegt
+# ausserhalb der Plugin-Ordner und wird vom LoxBerry-Installer NICHT geloescht,
+# muss also hier explizit weg.
+echo "<INFO> Entferne persistente Homebridge-Runtime unter $HB_RUNTIME_DIR."
+rm -rf "$HB_RUNTIME_DIR"
+
+echo "<OK> Homebridge-Dienst und Runtime entfernt."
+
 exit 0
